### PR TITLE
Upgrade Google Test and drop local skipped-test tracking

### PR DESCRIPTION
**Pull request by daviddrysdale**

### CODE REVIEW

**Comment by daviddrysdale** [comment]
@emaste, @ngie-eign, how would this PR affect things for FreeBSD?  In particular, is there a common FreeBSD-wide version of GoogleTest, and if so what version (and does it have `GTEST_SKIP` in it)?

**Comment by lwhsu** [comment]
@daviddrysdale thanks for taking care of this, in fact the patch in #43 was trying to upstream a patch committed in FreeBSD: https://svnweb.freebsd.org/changeset/base/358048

GTEST_SKIP was back ported to FreeBSD in https://svnweb.freebsd.org/changeset/base/345353

I am checking the flakey test on FreeBSD and found that some capsicum testcase have been marked skipped, however they are still executed and let the test program return non 0 value.

**Comment by lwhsu** [comment]
I think it's fine to let capsicum-test require newer gtest here. FreeBSD also have its enrolled version and we are currently using `GTEST_SKIP`. We can also check if upgrading the version FreeBSD enrolls will affect other tests.

**Comment by ngie-eign** [comment]
@daviddrysdale: the FreeBSD base system uses 1.8.1 with some modifications that backport GTEST_SKIP. Newer versions have additional features and compiler fixes which this project might benefit from.

Given that others have been backporting patches from googletest in FreeBSD, I think I should just upgrade to the latest version.

**Comment by emaste** [comment]
@ngie-eign are we using it beyond Google Test and FUSE tests in FreeBSD today? I would agree, updating Google Test in this repo is fine and we should migrate to the newer one in FreeBSD too.

**Comment by ngie-eign** [comment]
@emaste: not in the base system. Given that Googletest is a private library, I’m not concerned about tests outside of the base system.

CC:@asomers

**Pull request merged**
