### PR TITLE
Upgrade gtest from 1.6.0 to 1.8.1

### PR DESCRIPTION
**Pull request by ngie-eign**
This upgrades capsicum's embedded copy of Googletest to the latest supported
upstream version.

Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>

### CODE REVIEW

**Comment by ngie-eign** [comment]
CC: @emaste

**Comment by daviddrysdale** [comment]
Are you sure this is googletest 1.8.0 not 1.8.1?

Also, this removes the copy of gtest-1.6.0 under `casper/` but I don't think the build files are fully updated - I think `casper/tests/makefile` now refers to a non-existent directory and `casper/Makefile.am` needs updating too.

**Comment by ngie-eign** [comment]
> Are you sure this is googletest 1.8.0 not 1.8.1?

Thank you for the correction. I meant to use 1.8.1 consistently, but didn't. Will fix in the next push.

> Also, this removes the copy of gtest-1.6.0 under `casper/` but I don't think the build files are fully updated - I think `casper/tests/makefile` now refers to a non-existent directory and `casper/Makefile.am` needs updating too.

Will fix in the next push.

Would you object to me setting up a proper autoconf/automake system with this project, or would it make more sense to lean towards cmake (given where gtest and other google projects have gone)?

This code will also need to be re-ported to BSD/OSX. It unfortunately doesn't compile on either as-is. It might make sense to add travis CI support while I'm here to catch this in the future.

**Comment by ngie-eign** [comment]
@daviddrysdale: doing some digging around, it looks like some of the tests are written with a newer version of googletest in mind:
```
$ make
make  all-am
c++ -DHAVE_CONFIG_H -I.    -std=c++11 -Wall -g -I gtest-1.6.0/include -I gtest-1.6.0 -I src/libnv -I src/libpjdlog -I src/libcapsicum -DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_HAS_TR1_TUPLE=1 -g -O2 -MT tests/casper_test-testpjdlog.o -MD -MP -MF tests/.deps/casper_test-testpjdlog.Tpo -c -o tests/casper_test-testpjdlog.o `test -f 'tests/testpjdlog.cc' || echo './'`tests/testpjdlog.cc
tests/testpjdlog.cc:45:3: error: use of undeclared identifier 'EXPECT_DEATH'
  EXPECT_DEATH(pjdlog_prefix_pop(), "Assertion");
  ^
tests/testpjdlog.cc:52:3: error: use of undeclared identifier 'EXPECT_DEATH'
  EXPECT_DEATH(PJDLOG_ABORT("Aborting test"), "Aborting test");
  ^
2 errors generated.
*** Error code 1

Stop.
make[1]: stopped in /usr/home/ngie/nfs/git/capsicum-test/casper
*** Error code 1

Stop.
make: stopped in /usr/home/ngie/nfs/git/capsicum-test/casper
```

Can this change please move forward so I can focus on tackling other build issues on FreeBSD and OSX (there are at least a few)?

**Comment by ngie-eign** [comment]
@daviddrysdale: I did as you recommended in #26 and removed the casper changes from the PR.

**Comment by daviddrysdale** [comment]
I was still seeing some changes under `casper/gtest-1.6.0/` so I pushed an upgrade myself (as 12da2402dd74) &ndash; could you check that works for you?  Thanks.

**Comment by ngie-eign** [comment]
@daviddrysdale: yup -- that looks proper!

**Pull request closed without merging**
